lib/dh_sms_web/router.ex
defmodule DhSmsWeb.Router do
  use DhSmsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DhSmsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]

    post "/contacts/bulk", DhSmsWeb.ApiContactController, :bulk_create
  end

  scope "/", DhSmsWeb do
    pipe_through :browser

    resources "/campaigns", CampaignController do
      # resources "/conversations", ConversationController do
      #   resources "/contacts", ContactController
      #   resources "/messages", MessageController
      # end
    end

    resources "/contacts", ContactController



    live "/", PageLive, :index
  end

  scope "/webhooks", DhSmsWeb do
    resources "/messages", Webhooks.MessageController, only: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", DhSmsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DhSmsWeb.Telemetry
    end
  end
end

lib/dh_sms_web/views/layout_view.ex
defmodule DhSmsWeb.LayoutView do
  use DhSmsWeb, :view
end

lib/dh_sms_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/dh_sms_web/templates/layout/app.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/dh_sms_web/templates/layout/live.html.leex
<main role="main" class="container-fluid">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/dh_sms_web/templates/layout/nav.html.eex
<div class='navbar'>
    <ul>
        <li><%= link "Conversations", to: Routes.page_path(@conn, :index) %></li>
        <li><%= link "Campaigns", to: Routes.campaign_path(@conn, :index) %></li>
        <li><%= link "Contacts", to: Routes.contact_path(@conn, :index) %></li>
    </ul>
</div>

lib/dh_sms_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "DhSms", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
      <%= render "nav.html", assigns %>
    <%= @inner_content %>
  </body>
</html>